### ISSUE TITLE
Ability to (re-)create index from scratch

### ISSUE THREAD

**Issue by gyllstromk** [gyllstromk/Flask-WhooshAlchemy#10]

**Comment by noah** [comment]
Possibly relevant:

http://stackoverflow.com/a/28930121/67416

**Comment by rlam3** [comment]
https://gist.github.com/davb5/21fbffd7a7990f5e066c

**Comment by noah** [comment]
... The difference between the link @rlam3 posted and my code being that `model.query.all()` will load all rows into memory and so is useless for anything other than trivial data sets.
