### ISSUE TITLE
always get where null in whoosh_search

### ISSUE THREAD

**Issue by yndlsds** [gyllstromk/Flask-WhooshAlchemy#20]
I create Copmay Class like this:

```
from mysite import db
from .city import City
from .user import User

class Company(db.Model):
    __tablename__ = "Company"
    __searchable__ = ["name", "manager", "brief"]

    id        = db.Column(db.Integer, primary_key=True)
    #profile
    name      = db.Column(db.String(16), default="")    
    manager   = db.Column(db.String(8), default="")
    brief     = db.Column(db.String(140), default="")

    def __init__(self, *args, **kwargs):
        super(Company, self).__init__(*args, **kwargs)

import flask.ext.whooshalchemy as whooshalchemy
from mysite import app
whooshalchemy.whoosh_index(app, Company)
```

create company and then query with whoosh_search

```
c = Company.query.whoosh_search("example")
s = c.all()
```

I print c, but it show like "SELECT "Company".id AS "Company_id", ...... FROM "Company" WHERE null" and get s is [].

I think something was missing from my use of flask-whooshalchemy, althogh I followed the tutorial. please figure it out for me and thanks.

**Comment by nishchay2192** [comment]
One handy solution is to use the specific versions as mentioned in the following link and the whoosh_search should work fine:
https://github.com/gyllstromk/Flask-WhooshAlchemy/blob/master/requirements.txt
