### ISSUE TITLE
whoosh_search returns empty

### ISSUE THREAD

**Issue by timthejiang** [gyllstromk/Flask-WhooshAlchemy#21]
Tutorial at http://pythonhosted.org/Flask-WhooshAlchemy/ works for me.

Here's my setup

```
class Post(db.Model):
    __tablename__ = 'post'
    __searchable__ = ['body']

    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String)
```

Results:
- If I do not put `whoosh_index()` before `whoosh_search()`, I get the error:
  `AttributeError: 'BaseQuery' object has no attribute 'whoosh_search'`
- `db.session.query(Post).filter(Post.body=='hi')` returns the correct output with my data.
  `Post.query.whooshee_search('hi')` returns empty

I did leave some code out, like additional columns and backrefs, but that should not affect anything.

There are a few things to note:
- Tutorial worked fine without `whoosh_index()`, but my code threw error when I did not include it.
- `db.session.query(Post).filter()` code worked fine, indicating my model is at least somewhat correct, and there is something wrong with whoosh/my whoosh setup

I welcome any feedback, thanks

**Comment by scottydelta** [comment]
I am also facing the same bug, any solution?

**Comment by PrettyPrinted** [comment]
I just went through this, and I figured out it was because WhooshAlchemy relies on SQLAlchemy signals, which are enabled through the SQLALCHEMY_TRACK_MODIFICATIONS config value. I had it turned off to avoid the deprecation message, because I didn't need the functionality in my apps, but since WhooshAlchemy needs signals, you need it enabled.

**Comment by dhamaniasad** [comment]
Thanks for the advice @PrettyPrinted. Does this solve the issue for others too? @drahnr @scottydelta ?
