### ISSUE TITLE
“Query has no attribute 'whoosh_search”

### ISSUE THREAD

**Issue by samzhang111** [gyllstromk/Flask-WhooshAlchemy#25]
I left a StackOverflow question describing in more detail: http://stackoverflow.com/questions/24552415/query-has-no-attribute-whoosh-search-attributeerror-in-flask-whoosh-sqlal

I have read https://github.com/gyllstromk/Flask-WhooshAlchemy/issues/13 and https://github.com/miguelgrinberg/flasky/issues/8 and I'm still getting the same issue.

**Comment by ToonoW** [comment]
I think you setting is not correct.

According to [miguelgrinberg's blog](http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-x-full-text-search), after install Flask-WhooshAlchemy, you should  add `WHOOSH_BASE = os.path.join(basedir, 'search.db')` into file `config.py`. 
Then, add a new`__searchable__` field into model.
Then, `import flask.ext.whooshalchemy as whooshalchemy `  and `whooshalchemy.whoosh_index(app, Post)` in the file `__init__.py`.

At last, you can start to query you database.
