### ISSUE TITLE
Why pip install still install the version `0.5.6` while we do have `0.6`on pypi website.

### ISSUE THREAD

**Issue by huxuan** [gyllstromk/Flask-WhooshAlchemy#36]

**Comment by dhamaniasad** [comment]
:+1: I've only tested on OS X, but it does seem to be downloading `Flask-WhooshAlchemy-0.56` instead of the last `Flask-WhooshAlchemy-0.6`.

**Comment by stefanprobst** [comment]
The problem seems to be that the requirements were set to fixed versions after 0.56. Was there a specific reason for this?
