### ISSUE TITLE
Flask-SQLAlchemy version requirements 1.0 

### ISSUE THREAD

**Issue by fieldse** [gyllstromk/Flask-WhooshAlchemy#38]
Hi.
Installing from pip3, with currently installed version of Flask-SQLAlchemy at v2.0:
Installation fails with:
 _"No distributions matching the version for Flask-SQLAlchemy==1.0 (from Flask-WhooshAlchemy==0.6)"_

Do we have to downgrade from Flask-SQLAlchemy 2.0 to v 1.0?

**output from:  pip3 show Flask-SQLAlchemy**
Name: Flask-SQLAlchemy
Version: 2.0
Location: /usr/local/lib/python3.4/dist-packages
Requires: Flask, SQLAlchemy

Thanks!

**Comment by dhamaniasad** [comment]
Hi @fieldse,

I tried switching the package requirements from Flask-SQLAlchemy `1.0` to `2.0`, and the tests run successfully. 

```
pip freeze:
Flask==0.10.1
Flask-SQLAlchemy==2.0
Flask-Testing==0.4.2
Flask-WhooshAlchemy==0.6
Jinja2==2.7.3
MarkupSafe==0.23
SQLAlchemy==1.0.5
Werkzeug==0.10.4
Whoosh==2.6.0
blinker==1.3
itsdangerous==0.24
wsgiref==0.1.2
```

A quick look at the changelog between Flask-SQLAlchemy 1.0 and 2.0 tells me there are no breaking changes that would affect Flask-WhooshAlchemy, so Flask-SQLAlchemy 2.0 should work just fine.

**Comment by fieldse** [comment]
Thanks dude!
