### ISSUE TITLE
Rebuild index

### ISSUE THREAD

**Issue by jtl999** [gyllstromk/Flask-WhooshAlchemy#48]
What's a good way to manually rebuild the Whoosh index from an existing database after manually importing data into the database (outside of SQLAlchemy) or to ensure consistency of a database for example.

Thanks

**Comment by scottharman** [comment]
Ditto - I can see the index being created, but I have existing data that I'd like to index.

**Comment by dhamaniasad** [comment]
@jtl999 @scottharman You can give this gist a shot: https://gist.github.com/davb5/21fbffd7a7990f5e066c. Let me know if that solves your issue.
