### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by mosegontar** [gyllstromk/Flask-WhooshAlchemy#49]
Hi,

I was receiving the following deprecation warning when using Flask-WhooshAlchemy:

`ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.`

I was able to fix this by updating the line `import flask.ext.sqlalchemy as flask_sqlalchemy` in flask_whooshalchemy.py to `import flask_sqlachemy`, in order to accommodate the new extension import form.

**Comment by williamgibb** [comment]
This is closed in #53
