### ISSUE TITLE
whoosh_seach multi words??

### ISSUE THREAD

**Issue by tyan4g** [gyllstromk/Flask-WhooshAlchemy#51]
now I can search with
`results = BlogPost.query.whoosh_search('cool')`

but what if I want to search multi words at the same time??? like 
`results = BlogPost.query.whoosh_search('cool', 'happy', 'smile')`

Is this supported??

**Comment by dhamaniasad** [comment]
From the docs:

```python
results = BlogPost.query.whoosh_search('cool', or_=True)
```

If you do `whoosh_seach("cool happy smile")`, by default it will look for documents where all the three words are present. If you set `or_=True`, you will instead use the OR grouping.
