### ISSUE TITLE
ExtDeprecationWarning

### ISSUE THREAD

**Issue by rlam3** [gyllstromk/Flask-WhooshAlchemy#54]
``` bash
lib/python2.7/site-packages/flask/exthook.py:66: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  if fullname in sys.modules:
```

For those who are getting the following warning with the less up-to-date package pypi, you may use this:

pip uninstall flask-whooshalchemy
pip install git+git://github.com/rlam3/flask-whooshalchemy.git

But, I'd still highly suggest moving over to elasticsearch than using whoosh. Its just good to know. :) Cheers!

**Comment by williamgibb** [comment]
This is closed in #53
