### ISSUE TITLE
whoosh_index function runs _create_index on every call ignoring cache.

### ISSUE THREAD

**Issue by arabidopsis** [gyllstromk/Flask-WhooshAlchemy#58]
although the comment in whoosh index say that "gets the whoosh index for this model, creating one if it does not exist." the code  - lines (168-169) 

```
return app.whoosh_indexes.get(model.__name__,
                _create_index(app, model))
```

belies this comment.

**Comment by jrast** [comment]
Why do you think so? `_create_index` adds the newly created index to `app.whoosh_indexes`.

See https://github.com/gyllstromk/Flask-WhooshAlchemy/blob/master/flask_whooshalchemy.py#L209

**Comment by arabidopsis** [comment]
I was expecting something like:

```
if model.__name__ in app.whoosh_indexes:
      return app.whoosh_indexes[model.__name__]
else:
      return _create_index(app, model)
```

i.e. _create_index is only called if the model is _not_ in the app whoosh cache.

currently  `_create_index` is called _whether or not_ the model is in the app cache '`whoosh_indexes`'
-- since python is strict in its arguments i.e.`_create_index(app,model)` is called _before_ `app.whoosh_indexes.get` is ever called. No? Or is this what you want... I might have the wrong
end of the stick.

 BTW whoosh looks like an awesome package.

**Comment by jrast** [comment]
Oh, that's correct!
