### ISSUE TITLE
Python 3 Support.

### ISSUE THREAD

**Issue by saviour123** [gyllstromk/Flask-WhooshAlchemy#60]
It looks like its not python 3 compatible.

**Comment by jessejohnson** [comment]
I just run into this issue. I'm surprised it isn't sorted out.

**Comment by saviour123** [comment]
miguel has fixed it. 
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-x-full-text-search

**Comment by charlewn** [comment]
I tried the tutorial, but it's returning an empty list.

**Comment by weihaixiaoseu** [comment]
Is there any fork that is recommended to support python3 please? thanks

**Comment by duzhipeng** [comment]
> Is there any fork that is recommended to support python3 please? thanks

There is one:https://github.com/honmaple/flask-msearch

**Comment by babunoel** [comment]
Thanks @duzhipeng. I'm going to use flask-msearch. But before I do, can anyone tell me if it is any good to use!! Did anyone encounter any bugs? I'm only asking because it seem that the repo is quite recent.

**Comment by dhamaniasad** [comment]
Please switch to alternative libraries #69
