### ISSUE TITLE
AttributeError: module 'app' has no attribute 'config'

### ISSUE THREAD

**Issue by johnroper100** [gyllstromk/Flask-WhooshAlchemy#65]
I'm creating my config options using the form `app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False` but this causes a `AttributeError: module 'app' has no attribute 'config'` error. How can I fix this?

**Comment by dhamaniasad** [comment]
@johnroper100 were you able to figure it out? Sounds more like a flask issue than a Flask-WhooshAlchemy issue.
