### ISSUE TITLE
ModuleNotFoundError: No module named 'flask.ext'

### ISSUE THREAD

**Issue by therealrobster** [gyllstromk/Flask-WhooshAlchemy#66]
I'm trying to build via docker-compose and this is my error:

```
> web_1  |   File "/logrr/logrr/models.py", line 6, in <module>
> web_1  |     import flask_whooshalchemy as whooshalchemy
> web_1  |   File "/usr/local/lib/python3.7/site-packages/flask_whooshalchemy.py", line 18, in <module>
> web_1  |     import flask.ext.sqlalchemy as flask_sqlalchemy
> web_1  | ModuleNotFoundError: No module named 'flask.ext'

```

In my requirements.txt I have `flask_whooshalchemy` and am using `import flask_whooshalchemy as whooshalchemy` in my `models.py` file. 

Is the error my end or a bug?  I can't really tell

**Comment by zachvalenta** [comment]
looks like the same thing https://stackoverflow.com/a/53338666/6813490

**Comment by winnieshen96** [comment]
Can someone please fix this deprecation bug? If we need to edit the code to run whooshalchemy then we have to carry this edited whooshalchemy version to production as well, which is not ideal.

**Comment by dhamaniasad** [comment]
Hey folks,

Sorry for the trouble. I'll try and get a release out for this in the next few days. A PR would be welcome.

**Comment by dhamaniasad** [comment]
#68 will close this issue

**Comment by dhamaniasad** [comment]
Please switch to an alternative library: #69
